# Generated by Django 3.2.6 on 2021-08-04 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
